# Generated by Django 5.2.1 on 2025-07-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='twitter_access_token_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
